# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/MarkdownHome" # the subpath of your site, e.g. /blog
url: "https://liushihowe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  # - jekyll-feed  # removed to simplify site features
  - jekyll-seo-tag

highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  math_engine: mathjax

google_analytics: G-PCW3KNCFEN

# UI toggles
# Set to false to hide the global header and footer (still can override per-page if needed).
show_header_footer: false

# Site-wide date format (e.g. "September 28, 2025")
date_format: "%Y-%m-%d"

# Home page toggles
# Set to false to hide the posts list ("Posts" heading & RSS link) on the home page.
show_home_posts: false

# Font loading toggle
# Set to true to use locally hosted webfonts declared in assets/fonts/fonts.css
use_local_fonts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
